# Generated by Django 4.1.3 on 2022-12-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipsytastingapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquor',
            old_name='name',
            new_name='label',
        ),
    ]
