# Generated by Django 4.1.3 on 2022-12-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipsytastingapi', '0002_rename_name_liquor_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailpost',
            name='mixologist',
        ),
        migrations.RemoveField(
            model_name='cocktailpost',
            name='name',
        ),
        migrations.AlterField(
            model_name='cocktailliqueur',
            name='liqueur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='liqueur_needed_for_cocktail', to='tipsytastingapi.liqueur'),
        ),
    ]
