# Generated by Django 4.1.3 on 2023-01-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipsytastingapi', '0004_syrup_cocktailpost_liked_users_cocktailsyrup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktailsyrup',
            old_name='liqueur',
            new_name='syrup',
        ),
    ]
